name: sugar
channels:
  - pytorch3d
  - plotly
  - iopath
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - anyio
  - argon2-cffi
  - arrow
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - blas
  - bleach
  - brotli-python
  - bzip2
  - ca-certificates
  - cached-property
  - cached_property
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - cryptography
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-runtime
  - decorator
  - defusedxml
  - entrypoints
  - exceptiongroup
  - executing
  - ffmpeg
  - filelock
  - fqdn
  - freetype
  - fvcore
  - giflib
  - gmp
  - gmpy2
  - gnutls
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - iopath
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isoduration
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcusolver
  - libcusparse
  - libdeflate
  - libffi
  - libgcc
  - libgcc-ng
  - libgomp
  - libiconv
  - libidn2
  - libnpp
  - libnvjpeg
  - libpng
  - libsodium
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libwebp
  - libwebp-base
  - lz4-c
  - markdown-it-py
  - markupsafe
  - matplotlib-inline
  - mdurl
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - nbclient
  - nbconvert-core
  - ncurses
  - nettle
  - networkx
  - nodejs
  - notebook-shim
  - numpy
  - numpy-base
  - openh264
  - openjpeg
  - openssl
  - overrides
  - packaging
  - pandocfilters
  - parso
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - plotly
  - plyfile
  - portalocker
  - prometheus_client
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python_abi
  - pytorch
  - pytorch-cuda
  - pytorch-mutex
  - pytorch3d
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rich
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - sympy
  - tabulate
  - tbb
  - tenacity
  - termcolor
  - terminado
  - tinycss2
  - tk
  - tomli
  - torchaudio
  - torchtriton
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - types-python-dateutil
  - typing_extensions
  - typing_utils
  - uri-template
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xz
  - yacs
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - addict
      - ansi2html
      - blinker
      - click
      - comm
      - configargparse
      - contourpy
      - cycler
      - dash
      - dash-core-components
      - dash-html-components
      - dash-table
      - flask
      - fonttools
      - itsdangerous
      - joblib
      - kiwisolver
      - matplotlib
      - nbformat
      - nest-asyncio
      - open3d
      - pandas
      - pexpect
      - prompt-toolkit
      - pymcubes
      - pyparsing
      - pyquaternion
      - retrying
      - rpds-py
      - scikit-learn
      - scipy
      - stack-data
      - threadpoolctl
      - tzdata
      - werkzeug
